ingoControllers.controller('mainCtrl',
['$scope','ingoFactory',function($scope,ingoFactory){
  /*$scope.ingos = [
    {
      "nameEn":"A Jewish Contribution to an Inclusive Europe",
      "acronymEn":"CEJI",
      "nameFr":"Centre Européen Juif de l’Information",
      "acronymFr":"CEJI",
      "street":"",
      "postcode":"",
      "town":"Brussels",
      "country":"Belgium",
      "tel":"+ 32 (0)2 - 344 34 44",
      "fax":"+ 32 (0)2 - 344 67 35",
      "website":"www.ceji.org",
      "email":"",
      "funding":"Public funding",
      "natureOrganisation":"1",
      "presidentFirstname":"Alain",
      "presidentLastname":"Philippson",
      "presidentAddress":"",
      "sgFirstname":"Robin",
      "sgLastname":"Sclafani",
      "sgAddress":"",
      "yearFoundation":1991,
      "staff":"6",
      "nbMembers":"14",
      "workLang":"English",
      "officialLang":"French",
      "yearStatus":2007,
      "committes":"Democracy, Social Cohesion and Global Challenges, Education and Culture, Human Rights",
      "geoRep":"Austria, Belgium, Bulgaria, Czech Republic, Danemark, France, Germany, Greece, Hungary, Ireland, Italy, Luxembourg, Netherlands, Poland, Portugal, Spain, United Kingdom",
      "aims":"CEJI stands with individuals and organisations of all religions, cultures and backgrounds to promote a diverse and inclusive Europe. A Jewish voice at a European level, our activities include deliveri",
      "activities":"CEJI provides diversity education and training in Europe through ever-growing networks to offer a constructive response to prejudice and discrimination; Is at the forefront of the European Platform for the ..............",
      "constituency":"N/A",
      "accreditations":"Council of Europe, European Commission, European Parliament, United Nations World Conference Against Racism, European Network Against Racism",
      "publications":"See our website",
      "specPublications":"See our website",
      "annualReport":"Yes",
      "listPublications":"Yes",
      "aocs":"Democracy, Promotion of democratic values and education for democratic citizenship, Strengthening civil society, Education and Culture, Cultural diversity, Cultural policies, Education for Democratic Citizenship, Intercultural Dialogue, Other, Religion, Human rights, Children's rights, Fight against racism, Gender equality, Legal protection, Other, Promotion and defence of Human Rights, Rights of Minorities, International Co-operation, European integration, Other, Social Cohension, Children, Fight against poverty and social exclusion, Intercommunity relations and integration, Other, Students, Youth, Youth participation, Youth policy",
      "officialRep": [
        {
          "firstname":"Machin"
        }
      ]
    },
    {
      "nameEn":"Active - Sobriety, Friendship and Peace",
      "acronymEn":"Active",
      "nameFr":"Active - Sobriété, Paix et Amitié",
      "acronymFr":"Active",
      "street":"Gammelgardsvagen, 38",
      "postcode":"11297",
      "town":"Stockholm",
      "country":"Sweden",
      "tel":"+ 46 73 987 59 19",
      "fax":"",
      "website":"http://www.activeeurope.org",
      "email":"office@activeeurope.org",
      "funding":"",
      "natureOrganisation":"",
      "presidentFirstname":"",
      "presidentLastname":"",
      "presidentAddress":"",
      "sgFirstname":"",
      "sgLastname":"",
      "sgAddress":"",
      "yearFoundation":1990,
      "staff":"",
      "nbMembers":"",
      "workLang":"",
      "officialLang":"",
      "yearStatus":2015,
      "committes":"",
      "geoRep":"",
      "aims":"",
      "activities":"",
      "constituency":"",
      "accreditations":"",
      "publications":"",
      "specPublications":"",
      "annualReport":"No",
      "listPublications":"No",
      "aocs":""
    },
    {
      "nameEn":"Advice on Individual Rights in Europe – The AIRE Centre",
      "acronymEn":"AIRE",
      "nameFr":"Conseil en droits individuels en Europe - Centre AIRE",
      "acronymFr":"AIRE",
      "street":"Third Floor, 17 Red Lion Square",
      "postcode":"WC1R 4QH",
      "town":"London",
      "country":"United Kingdom",
      "tel":"+ 44 20 7831 4276",
      "fax":"+ 20 7404 7760",
      "website":"www.airecentre.org",
      "email":"info@airecentre.org",
      "funding":"",
      "natureOrganisation":"1",
      "presidentFirstname":"",
      "presidentLastname":"",
      "presidentAddress":"",
      "sgFirstname":"",
      "sgLastname":"",
      "sgAddress":"",
      "yearFoundation":0,
      "staff":"0",
      "nbMembers":"0",
      "workLang":"",
      "officialLang":"",
      "yearStatus":0,
      "committes":"",
      "geoRep":"",
      "aims":"",
      "activities":"",
      "constituency":"",
      "accreditations":"",
      "publications":"",
      "specPublications":"",
      "annualReport":"No",
      "listPublications":"No",
      "aocs":""
    },
    {
      "nameEn":"Age-Platform Europe",
      "acronymEn":"Age",
      "nameFr":"Age-Platform Europe",
      "acronymFr":"Age",
      "street":"Rue Froissart, 111",
      "postcode":"1040",
      "town":"Brussels",
      "country":"Belgium",
      "tel":"+ 32.2.280.14.70",
      "fax":"+ 32.2.280.15.22",
      "website":"www.age-platform.eu",
      "email":"info@age-platform.eu",
      "funding":"",
      "natureOrganisation":"1",
      "presidentFirstname":"",
      "presidentLastname":"",
      "presidentAddress":"",
      "sgFirstname":"Anne-Sophie",
      "sgLastname":"Parent",
      "sgAddress":"Rue Froissart, 111 - 1040 Brussels Belgium",
      "yearFoundation":0,
      "staff":"0",
      "nbMembers":"0",
      "workLang":"",
      "officialLang":"",
      "yearStatus":0,
      "committes":"",
      "geoRep":"",
      "aims":"",
      "activities":"",
      "constituency":"",
      "accreditations":"",
      "publications":"",
      "specPublications":"",
      "annualReport":"No",
      "listPublications":"No",
      "aocs":""
    },
    {
      "nameEn":"Alzheimer Europe",
      "acronymEn":"AE",
      "nameFr":"Alzheimer Europe",
      "acronymFr":"AE",
      "street":"145 route de Thionville",
      "postcode":"L-2611",
      "town":"Luxembourg",
      "country":"Luxembourg",
      "tel":"+352 297970",
      "fax":"+352 297972",
      "website":"www.alzheimer-europe.org",
      "email":"info@alzheimer-europe.org",
      "funding":"",
      "natureOrganisation":"1",
      "presidentFirstname":"Maurice",
      "presidentLastname":"O'Connell",
      "presidentAddress":"",
      "sgFirstname":"Jean",
      "sgLastname":"Georges",
      "sgAddress":"Alzheimer Europe 145 route de Thionville L-2611 Luxembour",
      "yearFoundation":1990,
      "staff":"5",
      "nbMembers":"28",
      "workLang":"French and English",
      "officialLang":"",
      "yearStatus":1999,
      "committes":"Democracy, Social Cohesion and Global Challenges, Education and Culture, Human Rights, Human Rights",
      "geoRep":"Austria, Belgium, Bulgaria, Czech Republic, Danemark, Spain, Finland, France, Germany, Hungary, Ireland, Italy, Netherlands, Norway, Poland, Portugal, Romania, Switzerland, Slovakia, Sweden, Turkey, Greece, Luxembourg, Malta, Iceland, United Kingdom",
      "aims":"",
      "activities":"",
      "constituency":"",
      "accreditations":"",
      "publications":"",
      "specPublications":"",
      "annualReport":"Yes",
      "listPublications":"Yes",
      "aocs":"Human rights, Education and Culture, Health"
    },
    {
      "nameEn":"Amnesty International",
      "acronymEn":"AI",
      "nameFr":"Amnesty International",
      "acronymFr":"AI",
      "street":"1 Easton Street",
      "postcode":"WC1X0DW",
      "town":"London",
      "country":"",
      "tel":"+44-20-74135500",
      "fax":"+44-20-79561157",
      "website":"www.amnesty.org",
      "email":"contactus@amnesty.org",
      "funding":"Private donations",
      "natureOrganisation":"",
      "presidentFirstname":"-",
      "presidentLastname":"-",
      "presidentAddress":"-",
      "sgFirstname":"Salil",
      "sgLastname":"Shetty",
      "sgAddress":"see above",
      "yearFoundation":1961,
      "staff":"0",
      "nbMembers":"0",
      "workLang":"",
      "officialLang":"",
      "yearStatus":1992,
      "committes":"Human Rights",
      "geoRep":"",
      "aims":"AI’s mission is to conduct research and generate action to prevent and end grave abuses of human rights and to demand justice for those whose rights have been violated.",
      "activities":"AI works to stop human rights abuses by mobilizing the public to put pressure on governments, armed political groups, companies and intergovernmental bodies via: publication and promotion of our resea",
      "constituency":"AI is a worldwide movement of people who campaign for internationally recognized human rights to be respected and protected for everyone. AI has more than 2.2 million members and subscribers in more t",
      "accreditations":"",
      "publications":"http://www.amnesty.org/en/library",
      "specPublications":"http://thereport.amnesty.org/eng/Homepage",
      "annualReport":"Yes",
      "listPublications":"Yes",
      "aocs":"Human rights"
    },
    {
      "nameEn":"ANDANTE, European Alliance of Catholic Women’s Organisations",
      "acronymEn":"ANDANTE",
      "nameFr":"ANDANTE, Alliance européenne d’organisations féminines catholiques",
      "acronymFr":"ANDANTE",
      "street":"",
      "postcode":"",
      "town":"Legal Seat in Düsseldorf, Germany",
      "country":"Germany",
      "tel":"",
      "fax":"",
      "website":"www.andante-europa.net",
      "email":"secretariat@andante-europa.net",
      "funding":"Membership fees",
      "natureOrganisation":"1",
      "presidentFirstname":"Mary",
      "presidentLastname":"McHugh",
      "presidentAddress":"",
      "sgFirstname":"",
      "sgLastname":"",
      "sgAddress":"1,2 mln. members at grasroot level",
      "yearFoundation":2006,
      "staff":"0",
      "nbMembers":"25",
      "workLang":"English, French, German",
      "officialLang":"",
      "yearStatus":2012,
      "committes":"Democracy, Social Cohesion and Global Challenges, Education and Culture, Human Rights",
      "geoRep":"Albania, Austria, Czech Republic, Finland, France, Germany, Hungary, Latvia, Luxembourg, Netherlands, Norway, Romania, Slovakia, Switzerland, United Kingdom",
      "aims":"",
      "activities":"",
      "constituency":"",
      "accreditations":"",
      "publications":"",
      "specPublications":"",
      "annualReport":"No",
      "listPublications":"No",
      "aocs":""
    },
    {
      "nameEn":"Anti-Slavery International",
      "acronymEn":"ASI",
      "nameFr":"Anti-Slavery International",
      "acronymFr":"ASI",
      "street":"Thomas Clarkson House, The Stableyard, Broomgrove",
      "postcode":"SW9 9TL",
      "town":"London",
      "country":"United Kingdom",
      "tel":"",
      "fax":"",
      "website":"www.antislavery.org",
      "email":"info@antislavery.org",
      "funding":"",
      "natureOrganisation":"1",
      "presidentFirstname":"",
      "presidentLastname":"",
      "presidentAddress":"",
      "sgFirstname":"",
      "sgLastname":"",
      "sgAddress":"",
      "yearFoundation":0,
      "staff":"0",
      "nbMembers":"0",
      "workLang":"",
      "officialLang":"",
      "yearStatus":0,
      "committes":"",
      "geoRep":"",
      "aims":"",
      "activities":"",
      "constituency":"",
      "accreditations":"",
      "publications":"",
      "specPublications":"",
      "annualReport":"No",
      "listPublications":"No",
      "aocs":""
    },
    {
      "nameEn":"Assembly of European Regions",
      "acronymEn":"AER",
      "nameFr":"Assemblée des Régions d'Europe",
      "acronymFr":"ARE",
      "street":"6 rue Oberlin",
      "postcode":"67000",
      "town":"Strasbourg",
      "country":"France",
      "tel":"+33 388 2207 07",
      "fax":"+33 388 7567 19",
      "website":"aer.eu",
      "email":"",
      "funding":"Member fees",
      "natureOrganisation":"1",
      "presidentFirstname":"Riccardo",
      "presidentLastname":"Illy",
      "presidentAddress":"Via Carducci 6 34133 Trieste (Italy)",
      "sgFirstname":"Klaus",
      "sgLastname":"Klipp",
      "sgAddress":"6 rue Oberlin 67000 Strasbourg",
      "yearFoundation":1986,
      "staff":"20",
      "nbMembers":"260",
      "workLang":"Français, Anglais, Allemand",
      "officialLang":"English, German, French",
      "yearStatus":0,
      "committes":"Democracy, Social Cohesion and Global Challenges, Education and Culture, Human Rights",
      "geoRep":"Belgium, France, Romania",
      "aims":"To promote the concept of regional democracy and subsidiarity in Europe To promote and lobby for the interests of regional governments in Europe",
      "activities":"",
      "constituency":"All regions in the countries represented at the Council of Europe",
      "accreditations":"",
      "publications":"Thematic Brochures, Annual reports, quarterly reports",
      "specPublications":"",
      "annualReport":"Yes",
      "listPublications":"Yes",
      "aocs":"Social Cohension, International Co-operation, Education and Culture, Health, Environment and sustanable development, Youth"
    }

  ]
  //  $scope
*/
$scope.ingos ='';
ingoFactory.aocsTransformed();
/*if(!ingoFactory.ingos){
    $scope.ingos = ingoFactory.getIngos();
}else {
    $scope.ingos = ingoFactory.ingos;
}*/
$scope.filters = true;
  ingoFactory.getIngos().then(
    function(data){
      $scope.ingos = data;
    },
    function(error){
      console.log( error.status);
    }
  );

  $scope.countries = ingoFactory.countries;
  $scope.aocs = ingoFactory.aocsTransformed("");
  $scope.committees = ingoFactory.committees;
}]);
